import PDFDocument from 'pdfkit';

export const generatePDF = (res, data) => {
  const { date, generatorCompany, works, totalEntries, totalQuantity, totalAmount } = data;

  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // Pipe the PDF document to the response
  doc.pipe(res);

  // Formatting utils
  const formatCurrency = (num) => {
    return 'Rs. ' + num.toLocaleString('en-IN');
  };
  
  // Custom font size and styles
  const drawLine = (y) => {
    doc.strokeColor('#aaaaaa')
       .lineWidth(1)
       .moveTo(50, y)
       .lineTo(545, y)
       .stroke();
  };

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text(generatorCompany, { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(16).text('DAILY WORK REPORT', { align: 'center' });
  doc.moveDown(1);
  
  // Date
  doc.fontSize(12).font('Helvetica').text(`Date: ${date.split('-').reverse().join('/')}`, { align: 'right' });
  doc.moveDown(1);

  // Table structure
  const tableTop = 200;
  const colSr = 50;
  const colCompany = 90;
  const colTool = 180;
  const colDesc = 270;
  const colQty = 400;
  const colRate = 440;
  const colAmount = 490;
  
  doc.font('Helvetica-Bold').fontSize(10);
  drawLine(tableTop - 10);
  
  doc.text('Sr', colSr, tableTop);
  doc.text('Company', colCompany, tableTop);
  doc.text('Tool', colTool, tableTop);
  doc.text('Description', colDesc, tableTop);
  doc.text('Qty', colQty, tableTop);
  doc.text('Rate', colRate, tableTop);
  doc.text('Amount', colAmount, tableTop);
  
  drawLine(tableTop + 15);
  
  doc.font('Helvetica').fontSize(10);
  let y = tableTop + 25;
  
  works.forEach((item, index) => {
    if (y > 700) {
      doc.addPage();
      y = 50;
      
      // Draw header again
      doc.font('Helvetica-Bold').fontSize(10);
      drawLine(y - 10);
      doc.text('Sr', colSr, y);
      doc.text('Company', colCompany, y);
      doc.text('Tool', colTool, y);
      doc.text('Description', colDesc, y);
      doc.text('Qty', colQty, y);
      doc.text('Rate', colRate, y);
      doc.text('Amount', colAmount, y);
      drawLine(y + 15);
      
      doc.font('Helvetica').fontSize(10);
      y = y + 25;
    }
    
    // Determine max height for this row based on multiline text
    const companyHeight = doc.heightOfString(item.companyName, { width: 80 });
    const toolHeight = doc.heightOfString(item.toolName, { width: 80 });
    const descHeight = doc.heightOfString(item.description, { width: 120 });
    
    const rowHeight = Math.max(companyHeight, toolHeight, descHeight, 15);

    doc.text((index + 1).toString(), colSr, y);
    doc.text(item.companyName, colCompany, y, { width: 80 });
    doc.text(item.toolName, colTool, y, { width: 80 });
    doc.text(item.description, colDesc, y, { width: 120 });
    doc.text(item.quantity.toString(), colQty, y);
    doc.text(item.rate.toString(), colRate, y);
    doc.text(formatCurrency(item.amount), colAmount, y);

    y += rowHeight + 10;
    drawLine(y - 5);
  });

  // Summary
  doc.moveDown(2);
  const summaryY = y + 20 < 700 ? y + 20 : 50;
  if (summaryY === 50) doc.addPage();

  doc.font('Helvetica-Bold').fontSize(12);
  doc.text('SUMMARY', 50, summaryY);
  
  doc.font('Helvetica').fontSize(11);
  doc.text(`Total Work Entries: ${totalEntries}`, 50, summaryY + 20);
  doc.text(`Total Quantity: ${totalQuantity}`, 50, summaryY + 40);
  doc.text(`Total Amount: ${formatCurrency(totalAmount)}`, 50, summaryY + 60);

  // Footer
  const totalPages = doc.bufferedPageRange ? doc.bufferedPageRange().count : 1;
  doc.fontSize(8).text(
    `Generated by ${generatorCompany} Work Tracking System`,
    50,
    780,
    { align: 'center', width: 500 }
  );

  doc.end();
};
